source 'https://rubygems.org'

gem 'rake'
gem 'pact_broker'
  unless RUBY_PLATFORM =~ /win32|x64-mingw32|x64-mingw-ucrt/
    gem 'sqlite3'
  else
    gem 'sqlite3', platforms: :ruby
  end
gem 'puma'
gem 'thin'
gem 'pry-byebug'
gem 'rackup'
gem "padrino-core", ">= 0.16.0.pre3" # Required for the pact_broker UI.
gem "pact-support"