source 'https://rubygems.org'

gem 'rake'
gem 'sqlite3'
gem 'puma'
gem 'thin'
gem 'pry-byebug'


if ENV["X_PACT_DEVELOPMENT"] == "true"
  gem "pact_broker", path: "../../pact_broker"
else
  gem "pact_broker", git: 'https://github.com/YOU54F/pact_broker.git', branch: 'feat/secrets-2'
end