source 'http://rubygems.org'

gem 'combustion'
gem 'faraday', '~> 1.0', '< 3.0'
gem 'rake', '~> 13'
gem 'rspec'
gem 'rspec-rails'
if ENV['X_PACT_DEVELOPMENT']
  gem 'sbmt-pact', path: '../../sbmt-pact'
else
  gem 'sbmt-pact', git: 'https://github.com/YOU54F/sbmt-pact.git', branch: 'feat/pact-ruby'
end
gem 'webmock'

gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw]
