source "http://rubygems.org"

if ENV['X_PACT_DEVELOPMENT']
  gem "sbmt-pact", path: '../../sbmt-pact'
else
  gem "sbmt-pact"
  gem 'combustion'
  gem 'webmock'
  gem 'rspec-rails'
end

gem "pact_broker-client"
gem "rake", "~> 12"
gem "rspec", "~> 3"
gem "faraday", "~> 1.0", "< 3.0"
gem "pry-byebug", "~> 3"
