source 'http://rubygems.org'


gem 'rake', '~> 13'

## for pact
gem 'rspec'
if ENV['X_PACT_DEVELOPMENT']
  gem 'sbmt-pact', path: '../../sbmt-pact'
else
  gem 'sbmt-pact', git: 'https://github.com/YOU54F/sbmt-pact.git', branch: 'feat/pact-ruby'
end
gem 'combustion'
gem 'webmock'

## for grpc
gem 'gruf', '>= 2.18'
gem 'gruf-rspec', '>= 0.6.0'
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw]
