source 'http://rubygems.org'

if ENV['X_PACT_DEVELOPMENT']
  gem 'sbmt-pact', path: '../../sbmt-pact'
else
  gem 'sbmt-pact', git: 'https://github.com/YOU54F/sbmt-pact.git', branch: 'feat/pact-ruby'
end

gem 'combustion'
gem 'rspec-rails'
gem 'webmock'

gem 'faraday'
gem 'pact_broker-client'
gem 'pry-byebug'
gem 'rake'
gem 'rspec'

gem 'tzinfo-data', platforms: [:windows]
