source 'http://rubygems.org'

if ENV['X_PACT_DEVELOPMENT']
  gem 'combustion'
  gem 'rspec-rails'
  gem 'sbmt-pact', path: '../../sbmt-pact'
  gem 'webmock'
else
  gem 'combustion'
  gem 'rspec-rails'
  gem 'sbmt-pact', git: 'https://github.com/YOU54F/sbmt-pact.git', branch: 'feat/pact-ruby'
  gem 'webmock'
end

gem 'faraday'
gem 'pact_broker-client'
gem 'pry-byebug'
gem 'rake'
gem 'rspec'

gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw]
