source 'http://rubygems.org'

if ENV['X_PACT_DEVELOPMENT']
  gem 'combustion'
  gem 'rspec-rails'
  gem 'sbmt-pact', path: '../../sbmt-pact'
  gem 'webmock'
else
  gem 'combustion'
  gem 'rspec-rails'
  gem 'sbmt-pact'
  gem 'webmock'
end

gem 'faraday', '~> 1.0', '< 3.0'
gem 'pact_broker-client'
gem 'pry-byebug', '~> 3'
gem 'rake', '~> 12'
gem 'rspec', '~> 3'
