require 'pact/tasks/verification_task'
require 'pact_broker/client/tasks'

LOCAL_PACT_BROKER_BASE_URL = 'http://localhost:9292'
REMOTE_PACT_BROKER_BASE_URL = 'https://test.pact.dius.com.au'

task :start_provider do
  system 'bundle exec rackup config.ru --pid provider.pid -D'
end

task :stop_provider do
  system 'kill $(cat provider.pid)'
end

# These pact publication tasks would normally be in the consumer codebase,
# but they're here so we can run the entire consumer/provider flow with one rake command.
PactBroker::Client::PublicationTask.new(:local) do | task |
  task.consumer_version = "1.0.0"
  task.pact_broker_base_url = LOCAL_PACT_BROKER_BASE_URL
  task.pattern = "consumer/spec/pacts/*.json"
end

PactBroker::Client::PublicationTask.new(:remote) do | task |
  task.consumer_version = "1.0.0"
  task.pact_broker_base_url = REMOTE_PACT_BROKER_BASE_URL
  task.pact_broker_basic_auth =  { username: ENV['PACT_BROKER_USERNAME'], password: ENV['PACT_BROKER_PASSWORD']}
  task.pattern = "consumer/spec/pacts/*.json"
end

Pact::VerificationTask.new(:foobar_pact) do |pact|
  pact.uri './consumer/spec/pacts/foo-bar.json', pact_helper: './provider/spec/pact_helper.rb'
end
task 'pact:verify:foobar' do
  Rake::Task['start_provider'].execute
  Rake::Task['pact:verify:foobar_pact'].execute
ensure
  Rake::Task['stop_provider'].execute
end

Pact::VerificationTask.new(:foobar_using_local_broker) do | pact |
  pact.uri "#{LOCAL_PACT_BROKER_BASE_URL}/pacts/provider/Bar/consumer/Foo/version/1.0.0", :pact_helper => './provider/spec/pact_helper.rb'
end

Pact::VerificationTask.new(:foobar_using_remote_broker) do | pact |
  pact.uri "#{REMOTE_PACT_BROKER_BASE_URL}/pacts/provider/Bar/consumer/Foo/version/1.0.0", :pact_helper => './provider/spec/pact_helper.rb'
end

task 'pact:set_publish_verification_results_flag' do
  ENV['PUBLISH_VERIFICATIONS_RESULTS'] = 'true'
end

task 'pact:verify:foobar_using_local_broker' => ['pact:set_publish_verification_results_flag', 'pact:publish:local']
task 'pact:verify:foobar_using_remote_broker' => ['pact:set_publish_verification_results_flag', 'pact:publish:remote']
