source 'http://rubygems.org'

gem 'rake', '~> 13'
gem 'rspec'

# for pact
gem 'sbmt-pact'
gem 'combustion'
gem 'webmock'

# for kafka
unless RUBY_PLATFORM =~ /win32|x64-mingw32|x64-mingw-ucrt/
  gem "sbmt-kafka_consumer", ">= 2.0.1"
  gem "sbmt-kafka_producer", ">= 1.0"
end
gem 'gruf', '>= 2.18'
gem 'gruf-rspec', '>= 0.6.0'

gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw]
