name: Test

on: [push, pull_request]

jobs:
  test_ruby:
    strategy:
      fail-fast: false
      matrix:
        ruby_version: ["2.7", "3.0", "3.1", "3.2", "3.3"]
        os: ["ubuntu-latest","windows-latest","macos-latest"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby_version }}
      - run: "bundle install"
      - run: "bundle exec rake spec"
      - run: "bundle exec rake pact:verify:foobar"
        if: matrix.os != 'windows-latest'
      - run: "bundle exec pact verify --provider-base-url http://localhost:9292 --pact-helper ./provider/spec/pact_helper.rb --pact-uri ./consumer/spec/pacts/foo-bar.json"
        if: matrix.os == 'windows-latest'
  test_ffi:
    strategy:
      fail-fast: false
      matrix:
        ruby_version: ["2.7", "3.0", "3.1", "3.2", "3.3"]
        os: ["ubuntu-latest","windows-latest","macos-latest"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby_version }}
      - run: "bundle install"
      - run: "bundle exec rake spec_ffi"
      - run: "bundle exec rake pact_ffi:verify:foobar"
        if: matrix.os != 'windows-latest'
      - run: "bundle exec pact verify-ffi --provider-base-url http://localhost:9292 --pact-helper ./provider/spec/pact_helper_ffi.rb --pact-uri ./consumer/spec/pacts/foo-bar.json"
        if: matrix.os == 'windows-latest'
