name: Test

on: [push, pull_request]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        ruby_version: ["2.7", "3.0", "3.1", "3.2", "3.3"]
        os: ["ubuntu-latest","windows-latest","macos-latest"]
        project: [e2e,e2e-pact-ruby-v1]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby_version }}
      - run: "bundle install"
        working-directory: ${{ matrix.project }}
      - run: "bundle exec rake spec"
        working-directory: ${{ matrix.project }}
      - run: "bundle exec rake pact:verify:foobar"
        working-directory: ${{ matrix.project }}
        if: matrix.os != 'windows-latest' && matrix.project != 'e2e-pact-ruby-v1'
      - run: "ruby.exe -S pact verify --pact-helper ./provider/spec/pact_helper.rb --pact-uri ./consumer/spec/pacts/foo-bar.json"
        working-directory: ${{ matrix.project }}
        if: matrix.os == 'windows-latest' && matrix.project == 'e2e-pact-ruby-v1'
